export default {
    FETCH_AIR_TEMP: 'FETCH_AIR_TEMP',
    FETCH_AIR_HUM: 'FETCH_AIR_HUM',
    FETCH_WATER_TEMP: 'FETCH_WATER_TEMP',
    FETCH_CAL_AIR_TEMP: 'FETCH_CAL_AIR_TEMP',
    FETCH_CAL_AIR_HUM: 'FETCH_CAL_AIR_HUM',
    FETCH_CAL_WATER_TEMP: 'FETCH_CAL_WATER_TEMP',
    SET_AIR_TEMP: 'SET_AIR_TEMP',
    SET_AIR_HUM: 'SET_AIR_HUM',
    SET_WATER_TEMP: 'SET_WATER_TEMP',
    SET_CAL_AIR_TEMP: 'SET_CAL_AIR_TEMP',
    SET_CAL_AIR_HUM: 'SET_CAL_AIR_HUM',
    SET_CAL_WATER_TEMP: 'SET_CAL_WATER_TEMP',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR'
}